# Generated by Django 2.2.4 on 2022-04-16 08:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='skill',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
