# Generated by Django 2.2.4 on 2022-04-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20220416_1131'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='skill',
            managers=[
            ],
        ),
    ]
