# Generated by Django 2.2.4 on 2022-04-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20220416_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='mobile1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='mobile2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
