# Generated by Django 2.2.4 on 2022-04-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20220417_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='mobile1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='mobile2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
