# Generated by Django 2.2.4 on 2022-04-18 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20220417_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='work.Governorate'),
        ),
        migrations.AlterField(
            model_name='community',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='work.Governorate'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='nickname',
            field=models.CharField(blank=True, default='nickname', max_length=45, null=True),
        ),
    ]
