# Generated by Django 2.2.4 on 2022-04-16 11:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='worker',
            managers=[
                ('objects1', django.db.models.manager.Manager()),
            ],
        ),
    ]
